sink("temp.txt")
library(BaylorEdPsych)
x_data <- subset(data,data$C14 > 0)
fitx<-glm(AN~FNDC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)

x_data <- subset(data,data$C7 > 0)
fitx<-glm(AN~FNDC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)

x_data <- subset(data,data$C6 > 0)
fitx<-glm(AN~FNDC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)

x_data <- subset(data,data$C14 > 0 | data$C6 > 0 | data$C7 > 0)
fitx<-glm(AN~FNDC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)
fitx<-glm(AN~FNDC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN+C6+C7, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)
sink()

library(BaylorEdPsych)
fitx<-glm(AN~FNCC+AB+TWC+CWC+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)


sink("temp.txt")
library(BaylorEdPsych)
x_data <- subset(data,data$C14 > 0)
fitx<-glm(AN~FNCC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)

x_data <- subset(data,data$C7 > 0)
fitx<-glm(AN~FNCC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)

x_data <- subset(data,data$C6 > 0)
fitx<-glm(AN~FNCC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)

x_data <- subset(data,data$C14 > 0 | data$C6 > 0 | data$C7 > 0)
fitx<-glm(AN~FNCC+AB+TWC+CWC+TAS+AS+TAP+AP+MEM+PN+C6+C7, data=x_data,  family=quasipoisson())
summary(fitx)
PseudoR2(fitx)
sink()